version: "3"

services:
  frontend:
    build: ./frontend
    container_name: tahours-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - funny-network

  backend:
    build: ./backend
    container_name: tahours-backend
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - funny-network

  database:
    image: mongo
    container_name: tahours-db
    stdin_open: true
    tty: true
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=scoobydoo123oliverthompson
      - MONGO_INITDB_ROOT_PASSWORD=scoobydoo123shaggy123fred123oliver
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./database/mongo-dump:/mongo-dump
      - tahours-data:/data/db
    networks:
      - funny-network


networks:
  funny-network:
    driver: bridge

volumes:
  tahours-data:
    driver: local
